- hosts: localhost
  become: yes
  remote_user: ansible
  become _method: sudo
  tasks:
    - name: create directory root nduka
      file:
        name: /home/ansible/nduka
        state: directory
        mode: 0775
